version: '3.1'

services:
  db:
    image: postgres:16-alpine
    hostname: nestjs-event-sourcing-db
    container_name: nestjs-event-sourcing-db
    restart: no
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 10s
      timeout: 30s
      retries: 5
